openapi: 3.0.2
info:
  title: ''
  version: ''
paths:
  /usersViewSet/:
    get:
      operationId: listUsers
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Users'
          description: ''
      tags:
      - usersViewSet
    post:
      operationId: createUsers
      description: ''
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Users'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Users'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Users'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Users'
          description: ''
      tags:
      - usersViewSet
  /usersViewSet/{wallet_number}/:
    get:
      operationId: retrieveUsers
      description: ''
      parameters:
      - name: wallet_number
        in: path
        required: true
        description: A unique value identifying this users.
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Users'
          description: ''
      tags:
      - usersViewSet
    put:
      operationId: updateUsers
      description: ''
      parameters:
      - name: wallet_number
        in: path
        required: true
        description: A unique value identifying this users.
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Users'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Users'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Users'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Users'
          description: ''
      tags:
      - usersViewSet
    patch:
      operationId: partialUpdateUsers
      description: ''
      parameters:
      - name: wallet_number
        in: path
        required: true
        description: A unique value identifying this users.
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Users'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Users'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Users'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Users'
          description: ''
      tags:
      - usersViewSet
    delete:
      operationId: destroyUsers
      description: ''
      parameters:
      - name: wallet_number
        in: path
        required: true
        description: A unique value identifying this users.
        schema:
          type: string
      responses:
        '204':
          description: ''
      tags:
      - usersViewSet
  /transactionViewSet/:
    get:
      operationId: listTransactions
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Transaction'
          description: ''
      tags:
      - transactionViewSet
    post:
      operationId: createTransaction
      description: ''
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Transaction'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Transaction'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Transaction'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transaction'
          description: ''
      tags:
      - transactionViewSet
  /transactionViewSet/{id}/:
    get:
      operationId: retrieveTransaction
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this transaction.
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transaction'
          description: ''
      tags:
      - transactionViewSet
    put:
      operationId: updateTransaction
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this transaction.
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Transaction'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Transaction'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Transaction'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transaction'
          description: ''
      tags:
      - transactionViewSet
    patch:
      operationId: partialUpdateTransaction
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this transaction.
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Transaction'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Transaction'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Transaction'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transaction'
          description: ''
      tags:
      - transactionViewSet
    delete:
      operationId: destroyTransaction
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this transaction.
        schema:
          type: string
      responses:
        '204':
          description: ''
      tags:
      - transactionViewSet
  /users/:
    get:
      operationId: listUsers
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items: {}
          description: ''
      tags:
      - users
    post:
      operationId: createUsers
      description: ''
      parameters: []
      requestBody:
        content:
          application/json:
            schema: {}
          application/x-www-form-urlencoded:
            schema: {}
          multipart/form-data:
            schema: {}
      responses:
        '201':
          content:
            application/json:
              schema: {}
          description: ''
      tags:
      - users
  /transactions/:
    get:
      operationId: listTransactions
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items: {}
          description: ''
      tags:
      - transactions
    post:
      operationId: createTransactions
      description: ''
      parameters: []
      requestBody:
        content:
          application/json:
            schema: {}
          application/x-www-form-urlencoded:
            schema: {}
          multipart/form-data:
            schema: {}
      responses:
        '201':
          content:
            application/json:
              schema: {}
          description: ''
      tags:
      - transactions
components:
  schemas:
    Users:
      type: object
      properties:
        wallet_number:
          type: integer
          readOnly: true
        username:
          type: string
          maxLength: 255
        password:
          type: string
          maxLength: 255
        total:
          type: integer
      required:
      - username
      - password
    Transaction:
      type: object
      properties:
        sender_wallet_number:
          type: string
        receiver_wallet_number:
          type: string
        transaction_amount:
          type: integer
      required:
      - sender_wallet_number
      - receiver_wallet_number
      - transaction_amount
