# Generated by Django 3.1.7 on 2021-03-26 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaymentSystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='wallet_number',
            field=models.BigIntegerField(default=183142171735, primary_key=True, serialize=False),
        ),
    ]
