# Generated by Django 3.1.7 on 2021-04-06 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaymentSystem', '0002_auto_20210406_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='wallet_number',
            field=models.CharField(default='d4f7e639-49fb-45ad-b343-88e57d8f7852', max_length=36, primary_key=True, serialize=False),
        ),
    ]
